/*
* @author Helga Hjartardóttir
 * heh54@hi.is
 * 29.mars 2015
 */
package Vidmot;

import Virkni.DiaryValues;
import is.hi.snorri.transport.Value;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/** DagbokGluggi heldur utan um vidmotshluta Forritsins
 * Dagatal.
 * 
 *  Forriti› var ﬂ‡tt og keyrt í Netbeans.
 */
public class DagbokGluggi extends javax.swing.JFrame {

    String currentDate;
    // currentDate segir til um hvada dagsetning valin er
    Value days;
    // days heldur utan um toflu sem geymir vidburdi
    VidburdurEvaluator v;
    // v er VidburdurEvaluator fyrir JCalendar hlutinn dagatal
    

    /**
     * DagbokGluggi heldur utan um initVirkni, initViduburdurEvaluator 
     * og initComponents 
     */
    public DagbokGluggi() {
        // Les inn töflu me› vi›bur›um og setur currentDate sem daginn í dag.
        initVirkni();
        // Byr til VidburdurEvaluator fyrir vidmotid
        initVidburdurEvaluator();
        // Frumstillir vi›mótshluti.
        initComponents();   
    }
    
    /**
     * initVidburdurEvaluator byr til VidburdurEvaluator og frumstillir toflu med vidburdum i honum
     */
    private void initVidburdurEvaluator() {
        v = new VidburdurEvaluator();
        v.setVidburdir(days);
    }
    
     /**
     * intiVirkni les inn töflu me› vi›bur›unum og setur currentDate sem daginn í dag
     */
    private void initVirkni() {
        days = DiaryValues.loadDays();
        currentDate = DiaryValues.dateToString(Calendar.getInstance().getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uppl = new javax.swing.JDialog();
        upplgluggi = new javax.swing.JScrollPane();
        upplysingatexti = new javax.swing.JTextArea();
        okei = new javax.swing.JButton();
        dagatal = new MyCalendar(v);
        vidburdirPanel = new javax.swing.JPanel();
        dagurVidburdar = new javax.swing.JLabel();
        skrolltime = new javax.swing.JScrollPane();
        time = new javax.swing.JList();
        vidburdirPane = new javax.swing.JScrollPane();

        vidburdir = new javax.swing.JTextArea();
        vidburdir.setText(DiaryValues.getDateText(days, currentDate));
        skóli = new javax.swing.JLabel();
        vinna = new javax.swing.JLabel();
        læknistimar = new javax.swing.JLabel();
        vinnaAtburdir = new javax.swing.JComboBox();
        skoliAtburdir = new javax.swing.JComboBox();
        læknistimarAtburdir = new javax.swing.JComboBox();
        atburdir = new javax.swing.JLabel();
        ymsirAtburdir = new javax.swing.JComboBox();
        minnism = new javax.swing.JScrollPane();
        minnismidi = new javax.swing.JTextArea();
        klukkan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        notepadMynd = new javax.swing.JLabel();
        vidburdamynd = new javax.swing.JLabel();
        eventmynd = new javax.swing.JLabel();
        minnis = new javax.swing.JLabel();
        hjalparbar = new javax.swing.JMenuBar();
        hjalp = new javax.swing.JMenu();
        upplysingar = new javax.swing.JMenuItem();

        uppl.setSize(new java.awt.Dimension(437, 350));

        upplysingatexti.setColumns(20);
        upplysingatexti.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        upplysingatexti.setRows(5);
        upplysingatexti.setText("Me› dagbók ﬂessari getur notandi skipulagt sig \nlangt fram í tímann me› skráningu vi›bur›a í \nvi›bur›arglugga. Dagar me› skrá›um vi›bur›um \nlitast me› bleikum lit og getur notandi ﬂannig\nfylgst me› ﬂeim dögum sem hann hefur skrá›a \nvi›bur›i á. \n\nJafnframt getur notandi skrá› minnispunkt inn á \nminnismi›a sem vistast sjálfkrafa er dagbókinni\ner loka› og birtist jafnframt aftur ﬂegar hún er \nopnu›. \n\nSkáning vi›bur›a: \nNotandi velur dag til a› skrá\nvi›bur› á. Hafi vi›bur›ur ákve›inn tíma getur\nnotandi vali› tíma úr tímalista vi› hli› vi›bur›-\narglugga. Tími birtist ﬂá í glugga og tvípunktur\nvi› hli› hans ﬂar sem notandi getur svo fært inn \nvi›bur›. \nNotanda til hæg›arauka eru nokkrir flokkar af \nvi›bur›um hægra megin vi› vi›bur›arglugga sem \nhægt er a› velja úr og skrifast ﬂá valinn \nvi›bur›ur inn í vi›bur›arglugga. \n");
        upplysingatexti.setFocusable(false);
        upplysingatexti.setLocation(new java.awt.Point(0, 0));
        upplysingatexti.setSize(new java.awt.Dimension(300, 300));
        upplgluggi.setViewportView(upplysingatexti);

        okei.setText("OK");
        okei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okeiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upplLayout = new javax.swing.GroupLayout(uppl.getContentPane());
        uppl.getContentPane().setLayout(upplLayout);
        upplLayout.setHorizontalGroup(
            upplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upplLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upplgluggi)
                .addContainerGap())
            .addGroup(upplLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(okei, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        upplLayout.setVerticalGroup(
            upplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upplLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upplgluggi, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okei)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dagbók Vi›mótsforritunar ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                keyraMinnismida(evt);
            }
        });

        dagatal.setBackground(new java.awt.Color(255, 255, 255));
        dagatal.setToolTipText("");
        dagatal.setDecorationBackgroundColor(new java.awt.Color(255, 204, 255));
        dagatal.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        dagatal.setPreferredSize(new java.awt.Dimension(600, 360));
        dagatal.setSundayForeground(new java.awt.Color(204, 0, 204));
        dagatal.setWeekdayForeground(new java.awt.Color(102, 0, 102));
        dagatal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dagatalPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout vidburdirPanelLayout = new javax.swing.GroupLayout(vidburdirPanel);
        vidburdirPanel.setLayout(vidburdirPanelLayout);
        vidburdirPanelLayout.setHorizontalGroup(
            vidburdirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        vidburdirPanelLayout.setVerticalGroup(
            vidburdirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dagurVidburdar.setFont(new java.awt.Font("Lucida Console", 0, 35)); // NOI18N
        dagurVidburdar.setForeground(new java.awt.Color(0, 153, 153));
        dagurVidburdar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dagurVidburdar.setText("Timi uppfærist");

        skrolltime.setForeground(new java.awt.Color(51, 255, 153));
        skrolltime.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        skrolltime.setMaximumSize(new java.awt.Dimension(23, 23));

        time.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        time.setForeground(new java.awt.Color(0, 0, 51));
        time.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skraTime(evt);
            }
        });
        skrolltime.setViewportView(time);

        vidburdir.setColumns(20);
        vidburdir.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        vidburdir.setRows(5);
        vidburdir.setToolTipText("");
        vidburdirPane.setViewportView(vidburdir);

        skóli.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        skóli.setForeground(new java.awt.Color(0, 204, 204));
        skóli.setText("Skóli");

        vinna.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        vinna.setForeground(new java.awt.Color(0, 153, 153));
        vinna.setText("Vinna");

        læknistimar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        læknistimar.setForeground(new java.awt.Color(0, 255, 255));
        læknistimar.setText("Læknist.");

        vinnaAtburdir.setForeground(new java.awt.Color(0, 102, 102));
        vinnaAtburdir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fundur", "Vakt", "Bakvakt" }));
        vinnaAtburdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraVinnuatburd(evt);
            }
        });

        skoliAtburdir.setForeground(new java.awt.Color(0, 204, 204));
        skoliAtburdir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tími", "Próf", "Ritger›", "Sk‡rsla", "Verkefni" }));
        skoliAtburdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraSkolaatburd(evt);
            }
        });

        læknistimarAtburdir.setForeground(new java.awt.Color(51, 255, 255));
        læknistimarAtburdir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Heimilislæknir", "Tannlæknir", "Hú›læknir", "Kvensjúkdómalæknir" }));
        læknistimarAtburdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skraLaeknisatburd(evt);
            }
        });

        atburdir.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        atburdir.setForeground(new java.awt.Color(51, 204, 255));
        atburdir.setText("†misl.");

        ymsirAtburdir.setForeground(new java.awt.Color(0, 153, 255));
        ymsirAtburdir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afmæli", "Brú›kaup", "Ferming", "Skírn", "Matarbo›", "Part‡" }));
        ymsirAtburdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ymsirAtburdirActionPerformed(evt);
            }
        });

        minnismidi.setBackground(new java.awt.Color(255, 255, 204));
        minnismidi.setColumns(20);
        minnismidi.setLineWrap(true);
        minnismidi.setRows(4);
        minnismidi.setTabSize(5);
        minnismidi.setPreferredSize(new java.awt.Dimension(80, 80));
        minnismidi.setSize(new java.awt.Dimension(50, 80));
        minnism.setViewportView(minnismidi);

        klukkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vidmot/c5b83ab8.png"))); // NOI18N

        notepadMynd.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        notepadMynd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vidmot/technology_internet_communications13-512.png"))); // NOI18N

        vidburdamynd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vidmot/timewise-today-icon.png"))); // NOI18N

        eventmynd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vidmot/EventsCalendar_Icon.png"))); // NOI18N

        minnis.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        minnis.setText("Til minnis:");

        hjalp.setText("Hjálp");

        upplysingar.setText("Hvernig skal nota dagbók");
        upplysingar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upplysingarActionPerformed(evt);
            }
        });
        hjalp.add(upplysingar);

        hjalparbar.add(hjalp);

        setJMenuBar(hjalparbar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dagatal, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(dagurVidburdar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(vidburdamynd))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(skrolltime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(klukkan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(vidburdirPane, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eventmynd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(læknistimarAtburdir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(skoliAtburdir, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                            .addComponent(vinnaAtburdir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(ymsirAtburdir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(atburdir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(læknistimar)
                                            .addComponent(skóli)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(vinna)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(notepadMynd)
                                .addGap(0, 0, 0)
                                .addComponent(minnis)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(minnism, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))))
                .addComponent(vidburdirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vidburdirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dagatal, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(dagurVidburdar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(notepadMynd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(minnis)
                                        .addGap(22, 22, 22)))
                                .addComponent(minnism, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vidburdamynd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(klukkan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(skrolltime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(vidburdirPane)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(eventmynd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vinna)
                                        .addGap(3, 3, 3)
                                        .addComponent(vinnaAtburdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(skóli)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(skoliAtburdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(læknistimar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(læknistimarAtburdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(atburdir)
                                        .addGap(3, 3, 3)
                                        .addComponent(ymsirAtburdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20))))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     /**
     * dagatalPropertyChange heldur utan um breytingar á dagatalinu
     */
    private void dagatalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dagatalPropertyChange

        // Ef dagsetningin sem vid vorum ad fara ur hefur vidburdi skrada
        // tha setjum vid vidburdinn i tofluna vid dagsetningu og vistum i skra
        if(DiaryValues.setDateText(days, currentDate, vidburdir.getText()))
            vistaISkra();
        // uppfaera currentDate med nyrri dagsetningu sem valin var
        currentDate = DiaryValues.dateToString(dagatal.getDate());
        //setur dagsetningu sem valin var í header á vi›bur›aglugga
        String dagsetning = new SimpleDateFormat("dd-MM-yyyy").format(dagatal.getDate());
        dagurVidburdar.setText(dagsetning);
        //nær i vidburdinn sem er geymdur fyrir  currentDate
        DiaryValues.getDateText(days, currentDate);
        // setja textann i vidburdarglugga
        vidburdir.setText(DiaryValues.getDateText(days, currentDate));
        //vi›mót uppfært
        dagatal.getDayChooser().updateUI();
        //uppfæra vi›móti› á deginum í dag - a›eins nau›synlegt ef vi›bur›ur á degi
        dagatal.getDayChooser().setDay(dagatal.getDayChooser().getDay());
    }//GEN-LAST:event_dagatalPropertyChange
    
    /**
     * Vistar value toflu, minnismi›a og lokar glugga thegar ytt er a loka-hnapp.
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        vistaISkra();
        geymaMinnis();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed
    /**
     * Skráir tíma sem valinn var í vi›bur›arglugga
     */
    private void skraTime(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skraTime
        String selected = time.getSelectedValue().toString();
        vidburdir.append(selected + ": "); 
        vidburdir.append("\n");
    }//GEN-LAST:event_skraTime

    private void ymsirAtburdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ymsirAtburdirActionPerformed
        String selected = ymsirAtburdir.getSelectedItem().toString();
        vidburdir.append(selected + " " + "\n" + "\n"); 
    }//GEN-LAST:event_ymsirAtburdirActionPerformed

    private void skraVinnuatburd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skraVinnuatburd
        String selected = vinnaAtburdir.getSelectedItem().toString();
        vidburdir.append(selected + " " + "\n" + "\n"); 
    }//GEN-LAST:event_skraVinnuatburd

    private void skraSkolaatburd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skraSkolaatburd
        String selected = skoliAtburdir.getSelectedItem().toString();
        vidburdir.append(selected + " " + "\n" + "\n"); 
    }//GEN-LAST:event_skraSkolaatburd

    private void skraLaeknisatburd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skraLaeknisatburd
        String selected = læknistimarAtburdir.getSelectedItem().toString();
        vidburdir.append(selected + " " + "\n" + "\n"); 
    }//GEN-LAST:event_skraLaeknisatburd
    // Geymir textann sem skrifa›ur er í minnismi›ann í minnismidi.txt
    private void geymaMinnis() 
    {
         FileWriter pw = null;
        try {
            pw = new FileWriter ("minnismidi.txt");
        } catch (IOException ex) {
            Logger.getLogger(DagbokGluggi.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            minnismidi.write(pw);
        } catch (IOException ex) {
            Logger.getLogger(DagbokGluggi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Nær í minnismidi.txt ﬂar sem textinn sem skrifa›ur hefur veri› í minnismi›ann er geymdur
    private void keyraMinnismida(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_keyraMinnismida
        FileReader reader = null;
        try {
            reader = new FileReader("minnismidi.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DagbokGluggi.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            minnismidi.read(reader,"minnismidi.txt");
        } catch (IOException ex) {
            Logger.getLogger(DagbokGluggi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_keyraMinnismida

    private void upplysingarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upplysingarActionPerformed
        uppl.setLocationRelativeTo(null);
        uppl.setVisible(true);
    }//GEN-LAST:event_upplysingarActionPerformed

    private void okeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okeiActionPerformed
        uppl.setVisible(false);
    }//GEN-LAST:event_okeiActionPerformed
/*   */ 
    /**
     * Vistar value tofluna i skra
     */
    private void vistaISkra() {
        try {
            // Beitum adferd saveDays(days) a klasann DiaryValues.
            DiaryValues.saveDays(days);
        } catch (IOException ex) {
            Logger.getLogger(DagbokGluggi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DagbokGluggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DagbokGluggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DagbokGluggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DagbokGluggi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DagbokGluggi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atburdir;
    public com.toedter.calendar.JCalendar dagatal;
    private javax.swing.JLabel dagurVidburdar;
    private javax.swing.JLabel eventmynd;
    private javax.swing.JMenu hjalp;
    private javax.swing.JMenuBar hjalparbar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel klukkan;
    private javax.swing.JLabel læknistimar;
    private javax.swing.JComboBox læknistimarAtburdir;
    private javax.swing.JLabel minnis;
    private javax.swing.JScrollPane minnism;
    private javax.swing.JTextArea minnismidi;
    private javax.swing.JLabel notepadMynd;
    private javax.swing.JButton okei;
    private javax.swing.JComboBox skoliAtburdir;
    private javax.swing.JScrollPane skrolltime;
    private javax.swing.JLabel skóli;
    private javax.swing.JList time;
    private javax.swing.JDialog uppl;
    private javax.swing.JScrollPane upplgluggi;
    private javax.swing.JMenuItem upplysingar;
    private javax.swing.JTextArea upplysingatexti;
    private javax.swing.JLabel vidburdamynd;
    private javax.swing.JTextArea vidburdir;
    private javax.swing.JScrollPane vidburdirPane;
    private javax.swing.JPanel vidburdirPanel;
    private javax.swing.JLabel vinna;
    private javax.swing.JComboBox vinnaAtburdir;
    private javax.swing.JComboBox ymsirAtburdir;
    // End of variables declaration//GEN-END:variables
}
